<!DOCTYPE html>
<html>
    <head>
        <title>Laravel PDF</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <style>
            body {
                float: left;
                font-family: "Open Sans", sans-serif;
                font-size: 11px; /* mengubah ukuran font */
                line-height: 0.8;
            }
            h1, h2 {
                font-weight: 400;
                margin: 0 0 20px;
            }
            table {

                border-collapse: collapse;
                width: 20%;
                margin-bottom: 20px;
            }
            table th, table td {
                border: 1px solid #ccc;
                padding: 8px;
                text-align: left;
                vertical-align: middle;
            }
            table th {
                background-color: #f2f2f2;
            }

            .title {
                font-family: "Pacifico", cursive;
                font-size: 36px;
                color: #006699;
                text-align: center;
                margin-bottom: 30px;
            }
            footer {
                margin-top: 50px;
                margin-bottom: 20px;
                text-align: center;
                color: #777;
                font-size: 12px;
                position: absolute;
                bottom: 0;
                width: 100%;
            }
            .container {
                max-width: 960px;
                margin: 0 auto;
            }
            @media print {
                table {

                    border-collapse: collapse;
                    width: 20%;
                    margin-bottom: 20px;
                    overflow-x: auto; /* menambahkan scroll horizontal */
                }
                table th, table td {
                    border: 1px solid #ccc;
                    padding: 5px; /* mengubah lebar kolom */
                    text-align: left;
                    vertical-align: middle;
                }
                table th {
                    background-color: #f2f2f2;
                }
                footer {
                    margin-top: 50px;
                    margin-bottom: 20px;
                    text-align: center;
                    color: #777;
                    font-size: 12px;
                    position: absolute;
                    bottom: 0;
                    width: 100%;
                }
            }
        </style>
    </head>
    <body>

        <div class="title">Rumah Sakit Cirebon</div>

        <div class="logo"></div>

        <div class="container">
            <h1 style="margin-top: 30px;text-align:center">Cetak Data Puskesmas</h1>

            <table class="table">
                <thead>
                  <tr>
                    <th>Kode KD</th>
                    <th>Kelurahan</th>
                    <th>Kode Puskesmas</th>
                    <th>Nama Puskesmas</th>
                    <th>Kode Kecamatan</th>
                    <th>Nama Kecamatan</th>
                    <th>Kode Kelurahan</th>
                  </tr>
                </thead>
                <tbody>
                    <?php


                    $i = 1;

                ?>


                    @foreach ($puskesmas_kecamatan_kelurahans as $row)
                    <tr>


                        <td>{{ old('kode_kd', $row->kode_kd) }}</td>
                        <td>{{$row->kelurahan}}</td>
                        <td>{{$row->kode_puskesmas}}</td>
                        <td>{{$row->nama_puskesmas}}</td>
                        <td>{{$row->kode_kecamatan}}</td>
                        <td>{{$row->nama_kecamatan}}</td>
                        <td>{{$row->kode_kelurahan}}</td>


                            <a href="/edit_data_puskesmas/{{$row->kode_kd}}"><i class="fas fa-pencil-alt" style="margin-right:5px"></i></a>
                            <form method="post" class="d-inline" action="/hapus_data_puskesmas">

                                <input type="hidden" name="kode_kd" value="{{$row->kode_kd}}">
                                <button class="btn" onclick="return confirm('Yakin mau menghapus?')"><i class="far fa-trash-alt"></i></button>
                            </form>

                    </tr>
                    @endforeach
                </tbody>
            </table>
            <footer>Generated by [Rumah Sakit Cirebon] on <?php echo date('Y-m-d H:i:s'); ?></footer>
        </body>
</html>
